# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: document.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'document.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ocument.proto\">\n\x15\x43reateDocumentRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x0finitial_content\x18\x02 \x01(\t\":\n\x16\x43reateDocumentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x12GetDocumentRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"H\n\x13GetDocumentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"C\n\x13\x45\x64itDocumentRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x01(\x05\x12\x0c\n\x04text\x18\x03 \x01(\t\"8\n\x14\x45\x64itDocumentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1d\n\rUpdateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"/\n\x0e\x44ocumentUpdate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2\x84\x02\n\x0f\x44ocumentService\x12\x41\n\x0e\x43reateDocument\x12\x16.CreateDocumentRequest\x1a\x17.CreateDocumentResponse\x12\x38\n\x0bGetDocument\x12\x13.GetDocumentRequest\x1a\x14.GetDocumentResponse\x12;\n\x0c\x45\x64itDocument\x12\x14.EditDocumentRequest\x1a\x15.EditDocumentResponse\x12\x37\n\x12SubscribeToUpdates\x12\x0e.UpdateRequest\x1a\x0f.DocumentUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEDOCUMENTREQUEST']._serialized_start=18
  _globals['_CREATEDOCUMENTREQUEST']._serialized_end=80
  _globals['_CREATEDOCUMENTRESPONSE']._serialized_start=82
  _globals['_CREATEDOCUMENTRESPONSE']._serialized_end=140
  _globals['_GETDOCUMENTREQUEST']._serialized_start=142
  _globals['_GETDOCUMENTREQUEST']._serialized_end=176
  _globals['_GETDOCUMENTRESPONSE']._serialized_start=178
  _globals['_GETDOCUMENTRESPONSE']._serialized_end=250
  _globals['_EDITDOCUMENTREQUEST']._serialized_start=252
  _globals['_EDITDOCUMENTREQUEST']._serialized_end=319
  _globals['_EDITDOCUMENTRESPONSE']._serialized_start=321
  _globals['_EDITDOCUMENTRESPONSE']._serialized_end=377
  _globals['_UPDATEREQUEST']._serialized_start=379
  _globals['_UPDATEREQUEST']._serialized_end=408
  _globals['_DOCUMENTUPDATE']._serialized_start=410
  _globals['_DOCUMENTUPDATE']._serialized_end=457
  _globals['_DOCUMENTSERVICE']._serialized_start=460
  _globals['_DOCUMENTSERVICE']._serialized_end=720
# @@protoc_insertion_point(module_scope)
